apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  targetNamespace: istio-system
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.2.5/charts/
    name: istio
    version: 1.2.5
  values:
    gateways:
      istio-ingressgateway:
        autoscaleMax: 1
        autoscaleMin: 1
        ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http
            nodePort: 31380
            port: 80
            targetPort: 80
          - name: https
            nodePort: 31390
            port: 443
          - name: ssh
            nodePort: 31400
            port: 22
        sds:
          enabled: true
    global:
      k8sIngress:
        enableHttps: true
        enabled: true
    grafana:
      enabled: true
    kiali:
      contextPath: /
      createDemoSecret: true
      dashboard:
        grafanaURL: http://grafana.${MY_DOMAIN}/
        jaegerURL: http://jaeger.${MY_DOMAIN}/
      enabled: true
    pilot:
      traceSampling: 100
    tracing:
      enabled: true
