name: VuePress build

on:
  push:
    branches:
    - master
    paths:
    - docs/*
    - .spelling
    - package.json

jobs:
  markdown_link_test:
    name: "Markdown link check"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: "Install Node.js 12"
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: "Install markdown-link-check"
      run: npm install -g markdown-link-check

    - name: "Create markdown-link-check configuration"
      run: |
        echo '{ "ignorePatterns": [ { "pattern": "^(http|https)://localhost" }, { "pattern": "^(http|https)://.*mylabs.dev" } ] }' > /tmp/config.json

    - name: "Run markdown-link-check"
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdown-link-check --config /tmp/config.json --quiet

  markdown_lint_check:
    name: "Markdown lint check"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: "Install Node.js 12"
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: "Install markdownlint-cli"
      run: npm install -g markdownlint-cli

    - name: "Create markdownlint configuration file"
      run: |
        echo "{ MD013: { code_blocks: false } }" > /tmp/markdownlint_config.json

    - name: "Run markdownlint"
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdownlint -c /tmp/markdownlint_config.json

  markdown_spell_check:
    name: "Markdown spell check"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: "Install Node.js 12"
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: "Install markdown-spellcheck"
      run: npm install -g markdown-spellcheck

    - name: "Run mdspell"
      run: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report --en-gb

  vuepress_build:
    name: "VuePress build"
    runs-on: ubuntu-latest

    needs:
      - markdown_link_test
      - markdown_lint_check
      - markdown_spell_check

    steps:
    - uses: actions/checkout@master

    - name: "Install Node.js 12"
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: "Install VuePress and build the document"
      run: |
        set -e
        npm install
        npm run build

    - name: "Check links"
      run: |
        set -e
        ln -s docs/.vuepress/dist ${GITHUB_REPOSITORY##*/}
        cp LICENSE docs/.vuepress/dist
        python3 -m http.server 8080 &> /dev/null &
        export HOST_IP_ADDRESS="$(ip -4 addr show docker0 | sed -n 's/.* inet \([^/]*\).*/\1/p')"
        docker run --rm linkchecker/linkchecker --pause=1 --check-extern --no-status --ignore-url "(http|https)://localhost" --ignore-url "(http|https)://.*mylabs.dev" http://${HOST_IP_ADDRESS}:8080/${GITHUB_REPOSITORY##*/}

  web_links_check:
    name: "Final links check"
    runs-on: ubuntu-latest

    needs:
      - vuepress_build

    steps:
    - uses: actions/checkout@master

    - name: "Install VuePress and build the document"
      run: docker run --rm linkchecker/linkchecker --pause=1 --check-extern --no-status --ignore-url "(http|https)://localhost" --ignore-url "(http|https)://.*mylabs.dev" https://${GITHUB_REPOSITORY%/*}.github.io/${GITHUB_REPOSITORY##*/}
